# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_auto_20171010_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 14, 13, 40, 773458, tzinfo=utc)),
        ),
    ]
