# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_auto_20171010_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('create_post', 'Can create post!'),)},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 14, 18, 17, 564693, tzinfo=utc)),
        ),
    ]
