# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_auto_20171011_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 4, 56, 56, 219253, tzinfo=utc)),
        ),
    ]
