# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 01:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0011_auto_20171011_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='healthstatus',
            name='patient',
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='patientid',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 1, 40, 44, 63261, tzinfo=utc)),
        ),
    ]
